### ISSUE TITLE
Crash Sometimes Occurs When Deleting Left Parentheses From Permutation

### ISSUE THREAD

**Issue by Potaszium** [wizgrao/sn#1]
Toying around with the website, I've gotten some crashes to occur when deleting the left parentheses from certain permutations. I think the leftmost permutation is usually safe, but other permutations sometimes cause crashes. I'm not sure exactly which ones cause crashes. Here's some examples where deleting the leftmost parentheses next to the cursor causes a crash:
![image](https://user-images.githubusercontent.com/15973060/197480887-03471cb9-57f0-4f3c-aba7-d6f0d7d7e2fa.png)
![image](https://user-images.githubusercontent.com/15973060/197480319-3e3fc72e-6604-49ec-9285-cfb9c47c9868.png)
![image](https://user-images.githubusercontent.com/15973060/197480461-7c4f472d-6a2d-4c9f-b883-83bd1c286de5.png)
![image](https://user-images.githubusercontent.com/15973060/197480749-a855e3e5-5c54-40a4-afa8-6ca9ab92b9e9.png)

--Jack

**Comment by wizgrao** [comment]
Thanks for pointing this out! #2 should fix this

For some context, the way I was parsing this was causing it to read that invalid string as like (3 2 2 3) or something. This isn't a valid permutation, and was causing one of the loops i was using to loop infinitely.

I changed the way i was parsing this slightly, and also added some checks to make sure the loops weren't running infinitely
